before:
  hooks:
  - go mod download

builds:
  - id: "hello-darwin-arm64"
    main: .
    binary: bin/hello
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    flags:
        - -tags=cgo,ledger,!test_ledger_mock,!ledger_mock,!ledger_zemu
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=crypto-org-chain -X github.com/cosmos/cosmos-sdk/version.ServerName=chain-maind -X github.com/cosmos/cosmos-sdk/version.ClientName=chain-maincli -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "hello-darwin"
    main: .
    binary: bin/hello
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    flags:
        - -tags=cgo,ledger,!test_ledger_mock,!ledger_mock,!ledger_zemu
  
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  builds:
  - hello-darwin-arm64
  - hello-darwin
checksum:
  name_template: 'checksumsmac.txt'


