name: goreleaser

on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
        xcode-version: '12.4'          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      - name: setup release environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release
      